# Generated by Django 5.1.2 on 2024-10-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=77)),
                ('email', models.TextField(max_length=77)),
                ('address', models.TextField(max_length=100)),
                ('contact', models.CharField(max_length=77)),
                ('password', models.CharField(max_length=77)),
            ],
        ),
    ]
